var cars = [{
        type: 'car',
        brand: 'Audi',
        model: 'A4',
        submodel: 'B8',
        year: 2009,
        horsepower: 143,
        space: 5,
        fuelType: 'Diesel',
        rating: 4.7,
        mileage: 220000,
        price: 70,
        imageLocation: 'alex_audi.jpg'
    }, {
        type: 'car',
        brand: 'Toyota',
        model: 'Corolla',
        submodel: 'SE',
        year: 2021,
        horsepower: 169,
        space: 5,
        fuelType: 'Gasoline',
        rating: 4.5,
        mileage: 10000,
        price: 28,
        imageLocation: 'Toyota-Corolla.jpg'
    }, {
        type: 'truck',
        brand: 'Ford',
        model: 'F-150',
        submodel: 'XL',
        year: 2022,
        horsepower: 290,
        space: 6,
        fuelType: 'Gasoline',
        rating: 4.9,
        mileage: 5000,
        price: 45,
        imageLocation: 'Ford-F-150.jpg'
    }, {
        type: 'suv',
        brand: 'Honda',
        model: 'CR-V',
        submodel: 'EX',
        year: 2020,
        horsepower: 190,
        space: 5,
        fuelType: 'Gasoline',
        rating: 4.7,
        mileage: 15000,
        price: 32,
        imageLocation: 'Honda-CR-V.jpg'
    }, {
        type: 'motorcycle',
        brand: 'Harley-Davidson',
        model: 'Softail',
        submodel: 'Heritage Classic',
        year: 2021,
        horsepower: 60,
        space: 2,
        fuelType: 'Gasoline',
        rating: 4.5,
        mileage: 5000,
        price: 20,
        imageLocation: 'Harley-Davidson-Softail.jpg'
    },
    {
        type: 'car',
        brand: 'BMW',
        model: '3 Series',
        submodel: '330i',
        year: 2022,
        horsepower: 255,
        space: 5,
        fuelType: 'Gasoline',
        rating: 4.9,
        mileage: 8000,
        price: 55,
        imageLocation: 'BMW-3-Series.jpg'
    },
    {
        type: 'truck',
        brand: 'Chevrolet',
        model: 'Silverado',
        submodel: '1500',
        year: 2021,
        horsepower: 285,
        space: 6,
        fuelType: 'Gasoline',
        rating: 4.7,
        mileage: 12000,
        price: 48,
        imageLocation: 'Chevrolet-Silverado.jpg'
    },
    {
        type: 'suv',
        brand: 'Ford',
        model: 'Explorer',
        submodel: 'ST',
        year: 2020,
        horsepower: 400,
        space: 7,
        fuelType: 'Gasoline',
        rating: 4.5,
        mileage: 20000,
        price: 50,
        imageLocation: 'Ford-Explorer.jpg'
    },
    {
        type: 'motorcycle',
        brand: 'Ducati',
        model: 'Panigale',
        submodel: 'V4',
        year: 2021,
        horsepower: 214,
        space: 2,
        fuelType: 'Gasoline',
        rating: 4.8,
        mileage: 1000,
        price: 30,
        imageLocation: 'Ducati-Panigale.jpg'
    },
    {
        type: 'car',
        brand: 'Mercedes-Benz',
        model: 'S-Class',
        submodel: 'S 580',
        year: 2022,
        horsepower: 496,
        space: 5,
        fuelType: 'Gasoline',
        rating: 5.0,
        mileage: 5000,
        price: 150,
        imageLocation: 'Mercedes-Benz-S-Class.jpg'
    },
    {
        type: 'car',
        brand: 'Lamborghini',
        model: 'Aventador',
        submodel: 'SVJ',
        year: 2022,
        horsepower: 770,
        space: 2,
        fuelType: 'Gasoline',
        rating: 4.9,
        mileage: 1500,
        price: 500,
        imageLocation: 'Lamborghini-Aventador-SVJ.jpg'
    },
    {
        type: 'car',
        brand: 'Bugatti',
        model: 'Chiron',
        submodel: 'Sport',
        year: 2022,
        horsepower: 1500,
        space: 2,
        fuelType: 'Gasoline',
        rating: 5.0,
        mileage: 300,
        price: 5000,
        imageLocation: 'Bugatti-Chiron-Sport.jpg'
    },
    {
        type: 'car',
        brand: 'McLaren',
        model: 'Senna',
        submodel: '',
        year: 2021,
        horsepower: 789,
        space: 2,
        fuelType: 'Gasoline',
        rating: 4.8,
        mileage: 1000,
        price: 1000,
        imageLocation: 'McLaren-Senna.jpg'
    },
    {
        type: 'race car',
        brand: 'Ferrari',
        model: 'SF21',
        submodel: '',
        year: 2021,
        horsepower: 950,
        space: 1,
        fuelType: 'Hybrid',
        rating: 4.9,
        mileage: 0,
        price: 'Not for sale',
        imageLocation: 'Ferrari-SF21.jpg'
    }, {
        type: 'car',
        brand: 'Toyota',
        model: 'Supra',
        submodel: '',
        year: 1995,
        horsepower: 320,
        space: 4,
        fuelType: 'Gasoline',
        rating: 4.7,
        mileage: 150000,
        price: 75,
        imageLocation: 'Toyota-Supra.jpg'
    }
];