var cars = [{
        id: 0,
        type: 'car',
        brand: 'Audi',
        model: 'A4',
        submodel: 'B8',
        year: 2009,
        horsepower: 143,
        space: 5,
        fuelType: 'Diesel',
        rating: 4.7,
        mileage: 220000,
        price: 70,
        imageLocation: ['alex_audi.jpg',"",""],
        aspects:['Luxury and Comfort','Performance and Power','Sleek and Stylish'],
        description:["The Audi A4 B8 2009 offers a premium driving experience with its leather interior, spacious cabin, and advanced technology features.",
       'With a 3.2-liter V6 engine delivering 265 horsepower, the Audi A4 B8 2009 provides impressive acceleration and a thrilling driving experience.',
    'The Audi A4 B8 2009 features a modern and refined design, with sleek lines and a striking grille that make it stand out on the road.']
    }, {
        id: 1,
        type: 'car',
        brand: 'Toyota',
        model: 'Corolla',
        submodel: 'SE',
        year: 2021,
        horsepower: 169,
        space: 5,
        fuelType: 'Gasoline',
        rating: 4.5,
        mileage: 10000,
        price: 28,
        imageLocation: ['Toyota-Corolla.jpg',"Toyota-Corolla3.jpg","Toyota-Corolla2.jpg"],
        aspects:["Sporty and Efficient","Tech-Savvy and Comfortable","Reliable and Affordable"],
        description:["The Toyota Corolla SE 2021 boasts a sporty design and a fuel-efficient engine, making it a perfect choice for those who want style and efficiency.",
        "Equipped with advanced technology features and a spacious cabin, the Toyota Corolla SE offers a comfortable and connected driving experience.",
        "Reliable and Affordable: Known for its reliability and affordability, the Toyota Corolla SE 2021 is a practical choice for anyone looking for a dependable car that won't break the bank."]
    }, {
        id: 2,
        type: 'truck',
        brand: 'Ford',
        model: 'F-150',
        submodel: 'XL',
        year: 2022,
        horsepower: 290,
        space: 6,
        fuelType: 'Gasoline',
        rating: 4.9,
        mileage: 5000,
        price: 45,
        imageLocation: ['Ford-F-150.jpg',"Ford-F-150_2.jpg","Ford-F-150_3.jpg"],
        aspects:["Powerful and Versatile","Comfortable and Spacious","Safe and Efficient"],
        description:["The Ford F-150 XL 2022 boasts a powerful engine and versatile capabilities, making it an excellent choice for work or play.",
        "Equipped with a roomy interior and comfortable seating, the Ford F-150 XL 2022 provides a comfortable and enjoyable ride for both drivers and passengers.",
        "With advanced safety features and impressive fuel efficiency, the Ford F-150 XL 2022 offers both peace of mind and cost savings for drivers."]
    }, {
        id: 3,
        type: 'suv',
        brand: 'Honda',
        model: 'CR-V',
        submodel: 'EX',
        year: 2020,
        horsepower: 190,
        space: 5,
        fuelType: 'Gasoline',
        rating: 4.7,
        mileage: 15000,
        price: 32,
        imageLocation: ['Honda-CR-V.jpg','',''],
        aspects:["Versatile and Practical","Advanced and Connected", "Efficient and Fun"],
        description:["The Honda CR-V EX 2020 is a versatile and practical crossover SUV that offers plenty of cargo space and a comfortable ride, making it perfect for families and adventurers alike.",
        "Equipped with advanced safety features and technology, the Honda CR-V EX 2020 provides a connected and secure driving experience. With features such as Honda Sensing and a touchscreen display audio system, drivers can enjoy peace of mind and convenience on the road.",
        "With its fuel-efficient engine and responsive handling, the Honda CR-V EX 2020 offers a fun and agile driving experience. Whether cruising around town or hitting the open road, the CR-V EX 2020 provides both efficiency and enjoyment."]
    }, {
        id: 4,
        type: 'motorcycle',
        brand: 'Harley-Davidson',
        model: 'Softail',
        submodel: 'Heritage Classic',
        year: 2021,
        horsepower: 60,
        space: 2,
        fuelType: 'Gasoline',
        rating: 4.5,
        mileage: 5000,
        price: 20,
        imageLocation: ['Harley-Davidson-Softail.jpg','',''],
        aspects:['Classic Style and Comfort','Powerful and Responsive','Customizable and Iconic'],
        description:['The Harley-Davidson Softail Heritage Classic 2021 combines classic Harley style with modern comfort features, providing riders with a stylish and comfortable ride.',
        'Featuring a powerful V-twin engine and responsive handling, the Harley-Davidson Softail Heritage Classic 2021 delivers a thrilling ride with excellent performance.',
        'With a range of customizable options and its iconic Harley-Davidson design, the Softail Heritage Classic 2021 allows riders to make a statement on the road with a personalized motorcycle.']
    },
    {
        id: 5,
        type: 'car',
        brand: 'BMW',
        model: '3 Series',
        submodel: '330i',
        year: 2022,
        horsepower: 255,
        space: 5,
        fuelType: 'Gasoline',
        rating: 4.9,
        mileage: 8000,
        price: 55,
        imageLocation: ['BMW-3-Series.jpg','',''],
        aspects:['Dynamic and Sporty','Luxurious and Comfortable','Efficient and Eco-Friendly'],
        description:['The BMW 3 Series 330i 2022 offers a thrilling driving experience with its powerful engine, responsive handling, and sporty design.',
        'With its premium materials, advanced technology, and spacious interior, the BMW 3 Series 330i 2022 provides a luxurious and comfortable ride for drivers and passengers alike.',
        'Equipped with a fuel-efficient engine and advanced hybrid technology, the BMW 3 Series 330i 2022 is an eco-friendly choice for drivers who want to reduce their carbon footprint without sacrificing performance.']
    },
    {
        id: 6,
        type: 'truck',
        brand: 'Chevrolet',
        model: 'Silverado',
        submodel: '1500',
        year: 2021,
        horsepower: 285,
        space: 6,
        fuelType: 'Gasoline',
        rating: 4.7,
        mileage: 12000,
        price: 48,
        imageLocation: ['Chevrolet-Silverado.jpg','',''],
        aspects:['Powerful and Versatile','Comfortable and Spacious','Modern and Stylish'],
        description:['The Chevrolet Silverado 1500 is built to handle tough jobs with its powerful engine and versatile cargo bed, making it a top choice for truck enthusiasts and professionals alike.',
        'Featuring a roomy cabin and advanced technology, the Chevrolet Silverado 1500 provides a comfortable and convenient ride for drivers and passengers, whether on short commutes or long road trips.',
        'With its sleek and modern design, the Chevrolet Silverado 1500 is a stylish and eye-catching truck that turns heads on the road, while still delivering impressive performance and functionality.']
    },
    {
        id: 7,
        type: 'suv',
        brand: 'Ford',
        model: 'Explorer',
        submodel: 'ST',
        year: 2020,
        horsepower: 400,
        space: 7,
        fuelType: 'Gasoline',
        rating: 4.5,
        mileage: 20000,
        price: 50,
        imageLocation: ['Ford-Explorer.jpg','',''],
        aspects:['Powerful and Athletic','Spacious and Versatile','Luxurious and High-Tech'],
        description:['With a turbocharged V6 engine and all-wheel drive, the Ford Explorer ST 2020 delivers an exhilarating driving experience with impressive acceleration and handling.',
        'Featuring three rows of seating and ample cargo space, the Ford Explorer ST 2020 is a practical choice for families on the go, offering plenty of room for passengers and gear.',
        'Equipped with premium features like leather upholstery and a 12.3-inch digital instrument cluster, the Ford Explorer ST 2020 delivers a comfortable and high-tech driving experience that rivals luxury SUVs.']
    },
    {
        id: 8,
        type: 'motorcycle',
        brand: 'Ducati',
        model: 'Panigale',
        submodel: 'V4',
        year: 2021,
        horsepower: 214,
        space: 2,
        fuelType: 'Gasoline',
        rating: 4.8,
        mileage: 1000,
        price: 30,
        imageLocation: ['Ducati-Panigale.jpg','',''],
        aspects:['Powerful and Agile','Sleek and Stylish','Innovative and High-Tech'],
        description:['With a high-performance engine and advanced suspension, the Ducati Panigale V4 2021 offers a thrilling and responsive ride for motorcycle enthusiasts who crave speed and agility.',
        'Boasting a sleek and aerodynamic design, the Ducati Panigale V4 2021 is a head-turner on the road, with its unmistakable Italian style and distinctive red color scheme.',
        'Featuring state-of-the-art technology such as an advanced digital dashboard and sophisticated electronics package, the Ducati Panigale V4 2021 offers riders the ultimate in connectivity and convenience.']
    },
    {
        id: 9,
        type: 'car',
        brand: 'Mercedes-Benz',
        model: 'S-Class',
        submodel: 'S 580',
        year: 2022,
        horsepower: 496,
        space: 5,
        fuelType: 'Gasoline',
        rating: 5.0,
        mileage: 5000,
        price: 150,
        imageLocation: ['Mercedes-Benz-S-Class.jpg','',''],
        aspects:['Luxurious and High-Tech','Powerful and Dynamic','Spacious and Elegant'],
        description:['The Mercedes-Benz S-Class S 580 2022 boasts a luxurious interior with cutting-edge technology and features, making it a top choice for drivers who prioritize comfort and convenience.',
        "With its high-performance engine and smooth handling, the Mercedes-Benz S-Class S 580 2022 offers a thrilling driving experience that's sure to impress any car enthusiast.",
        "With plenty of legroom and a stylish exterior design, the Mercedes-Benz S-Class S 580 2022 is a spacious and sophisticated sedan that's perfect for long drives and special occasions."]
    },
    {
        id: 10,
        type: 'car',
        brand: 'Lamborghini',
        model: 'Aventador',
        submodel: 'SVJ',
        year: 2022,
        horsepower: 770,
        space: 2,
        fuelType: 'Gasoline',
        rating: 4.9,
        mileage: 1500,
        price: 500,
        imageLocation: ['Lamborghini-Aventador-SVJ.jpg','',''],
        aspects:['Uncompromising Performance','Precision Handling','Exotic Design'],
        description:['The Lamborghini Aventador SVJ 2022 is a true supercar, with a powerful V12 engine and lightning-fast acceleration that delivers an adrenaline-pumping driving experience.',
        'With its advanced aerodynamics and precision handling, the Lamborghini Aventador SVJ 2022 offers unparalleled control and maneuverability, making it the ultimate choice for drivers who demand the very best.',
        'From its dramatic lines to its signature scissor doors, the Lamborghini Aventador SVJ 2022 is a work of art that commands attention and turns heads wherever it goes.']
    },
    {
        id: 11,
        type: 'car',
        brand: 'Bugatti',
        model: 'Chiron',
        submodel: 'Sport',
        year: 2022,
        horsepower: 1500,
        space: 2,
        fuelType: 'Gasoline',
        rating: 5.0,
        mileage: 300,
        price: 5000,
        imageLocation: ['Bugatti-Chiron-Sport.jpg','',''],
        aspects:['Unmatched Performance','Luxurious and Exclusive','Incredible Design'],
        description:["With a top speed of over 490 km/h and 1500 horsepower, the Bugatti Chiron Sport 2022 is a true engineering marvel, pushing the limits of what's possible in a street-legal supercar.",
        "The Bugatti Chiron Sport 2022 offers a one-of-a-kind driving experience, with a meticulously crafted interior featuring the finest materials and unparalleled attention to detail.",
        "The Bugatti Chiron Sport 2022 is not just a car, it's a work of art. From its striking lines to its aerodynamic curves, every aspect of the design has been carefully considered to create a vehicle that is both beautiful and functional."]
    },
    {
        id: 12,
        type: 'car',
        brand: 'McLaren',
        model: 'Senna',
        submodel: '',
        year: 2021,
        horsepower: 789,
        space: 2,
        fuelType: 'Gasoline',
        rating: 4.8,
        mileage: 1000,
        price: 1000,
        imageLocation: ['McLaren-Senna.jpg','',''],
        aspects:['Exclusive and Iconic','Pure Performance','Lightweight and Nimble'],
        description:["With only 500 units produced worldwide, the McLaren Senna 2021 is a rare and highly sought-after supercar. Its unique design and exclusivity make it a true collector's item for automotive enthusiasts.",
        'Designed for speed and agility, the McLaren Senna 2021 is a true performance machine. Its aerodynamic body and powerful engine make it an exhilarating ride for any driving enthusiast.',
        'Weighing in at just 2,641 pounds, the McLaren Senna 2021 is one of the lightest supercars on the market. Its agile handling and quick acceleration make it a joy to drive on any road or track.']
    },
    {
        id: 13,
        type: 'race car',
        brand: 'Ferrari',
        model: 'SF21',
        submodel: '',
        year: 2021,
        horsepower: 950,
        space: 1,
        fuelType: 'Hybrid',
        rating: 4.9,
        mileage: 0,
        price: 'Not for sale',
        imageLocation: ['Ferrari-SF21.jpg','',''],
        aspects:['High-Performance and Stylish','Innovative and Aerodynamic','Luxurious and Sophisticated'],
        description:['The Ferrari SF21 2021 is a top-performing sports car with an eye-catching design, perfect for drivers who want to make a statement on the road.',
        'The Ferrari SF21 2021 features advanced aerodynamic technology, giving it unparalleled speed and precision on the track.',
        'The Ferrari SF21 2021 boasts a luxurious interior with high-quality materials, making it a comfortable and sophisticated ride for drivers and passengers alike.']
    }, {
        id: 14,
        type: 'car',
        brand: 'Toyota',
        model: 'Supra',
        submodel: '',
        year: 1995,
        horsepower: 320,
        space: 4,
        fuelType: 'Gasoline',
        rating: 4.7,
        mileage: 150000,
        price: 75,
        imageLocation: ['Toyota-Supra.jpg','',''],
        aspects:['Sporty and Agile','Sleek and Stylish','Reliable and Durable'],
        description:['The Toyota Supra 1995 offers a thrilling driving experience thanks to its turbocharged engine and agile handling.',
        'With its iconic design and smooth lines, the Toyota Supra 1995 remains a classic sports car that turns heads wherever it goes.',
        "Known for its durability and reliability, the Toyota Supra 1995 is a testament to Toyota's commitment to quality engineering and craftsmanship."]
    },
    {
        id: 15,
        type: 'suv',
        brand: 'Audi',
        model: 'Q5',
        submodel: '2.0T Premium',
        year: 2018,
        horsepower: 252,
        space: 5,
        fuelType: 'Gasoline',
        rating: 4.6,
        mileage: 45000,
        price: 38,
        imageLocation: ['', '', ''],
        aspects: ['Luxurious Interior', 'Advanced Technology', 'Versatile Performance'],
        description: ["The Audi Q5 2.0T Premium 2018 offers a luxurious interior with high-quality materials, comfortable seating, and ample cargo space, making it perfect for both everyday commuting and adventurous getaways.",
          "Featuring advanced technology and connectivity options, such as Audi Virtual Cockpit and MMI infotainment system, the Audi Q5 2.0T Premium 2018 keeps you connected and entertained on the road.",
          "Powered by a 2.0-liter turbocharged engine delivering 252 horsepower, the Audi Q5 2.0T Premium 2018 provides a perfect balance of performance and efficiency, ensuring a thrilling driving experience."]
      },
      {
        id: 16,
        type: 'car',
        brand: 'Audi',
        model: 'A6',
        submodel: '3.0T Quattro',
        year: 2020,
        horsepower: 335,
        space: 5,
        fuelType: 'Gasoline',
        rating: 4.8,
        mileage: 20000,
        price: 55,
        imageLocation: ['audi_a6.jpg', '', ''],
        aspects: ['Elegant Design', 'Powerful Performance', 'Cutting-Edge Technology'],
        description: ["The Audi A6 3.0T Quattro 2020 showcases an elegant design with sleek lines and a spacious and comfortable cabin, providing a sophisticated and luxurious driving experience.",
          "Equipped with a 3.0-liter V6 engine producing 335 horsepower, the Audi A6 3.0T Quattro 2020 delivers exhilarating performance and impressive acceleration, making it a joy to drive.",
          "With its advanced technology features, including a fully digital cockpit and an intuitive infotainment system, the Audi A6 3.0T Quattro 2020 keeps you connected and in control on every journey."]
      },
      {
        id: 17,
        type: 'car',
        brand: 'Toyota',
        model: 'Camry',
        submodel: 'SE',
        year: 2022,
        horsepower: 206,
        space: 5,
        fuelType: 'Gasoline',
        rating: 4.5,
        mileage: 15000,
        price: 28,
        imageLocation: ['toyota_camry.jpg', '', ''],
        aspects: ['Reliability and Efficiency', 'Sporty and Stylish', 'Advanced Safety'],
        description: ["The Toyota Camry SE 2022 offers reliable performance and excellent fuel efficiency, making it a practical choice for daily commuting and long drives.",
          "With its sporty design elements and sleek lines, the Toyota Camry SE 2022 exudes a sense of style and sophistication, turning heads on the road.",
          "Equipped with advanced safety features, such as Toyota Safety Sense™ P, the Toyota Camry SE 2022 provides peace of mind and enhanced driver-assistance for a safer driving experience."]
      },
      {
        id: 18,
        type: 'suv',
        brand: 'Toyota',
        model: 'RAV4',
        submodel: 'XLE',
        year: 2021,
        horsepower: 203,
        space: 5,
        fuelType: 'Gasoline',
        rating: 4.7,
        mileage: 25000,
        price: 32,
        imageLocation: ['toyota_rav4.jpg', '', ''],
        aspects: ['Versatile and Practical', 'Modern Design', 'Advanced Technology'],
        description: ["The Toyota RAV4 XLE 2021 offers versatility and practicality, with ample cargo space and available all-wheel drive, making it suitable for both city driving and outdoor adventures.",
          "Featuring a modern and dynamic design, the Toyota RAV4 XLE 2021 stands out with its bold lines and aggressive front grille, making a statement on the road.",
          "Equipped with advanced technology, including a touchscreen infotainment system and available Apple CarPlay® and Android Auto™ integration, the Toyota RAV4 XLE 2021 keeps you connected and entertained wherever you go."]
      },
      {
        id: 19,
        type: 'suv',
        brand: 'Toyota',
        model: 'Highlander',
        submodel: 'Limited',
        year: 2023,
        horsepower: 295,
        space: 7,
        fuelType: 'Gasoline',
        rating: 4.8,
        mileage: 10000,
        price: 45,
        imageLocation: ['toyota_highlander.jpg', '', ''],
        aspects: ['Spacious and Comfortable', 'Luxurious Features', 'Advanced Safety'],
        description: ["The Toyota Highlander Limited 2023 offers spacious and comfortable seating for up to seven passengers, with premium materials and amenities that ensure a luxurious and enjoyable ride.",
          "With its elegant design and attention to detail, the Toyota Highlander Limited 2023 creates a sophisticated and refined presence on the road, turning heads wherever it goes.",
          "Equipped with advanced safety features, including Toyota Safety Sense™ 2.5+, the Toyota Highlander Limited 2023 provides enhanced protection and peace of mind for both the driver and passengers."]
      },
      {
        id: 20,
        type: 'car',
        brand: 'Ford',
        model: 'Mustang',
        submodel: 'GT Premium',
        year: 2022,
        horsepower: 450,
        space: 4,
        fuelType: 'Gasoline',
        rating: 4.9,
        mileage: 5000,
        price: 45,
        imageLocation: ['ford_mustang.jpg', '', ''],
        aspects: ['Muscular Performance', 'Iconic Design', 'Cutting-Edge Technology'],
        description: ["The Ford Mustang GT Premium 2022 offers a thrilling driving experience with its powerful 5.0-liter V8 engine delivering 450 horsepower, providing exhilarating acceleration and a commanding performance.",
          "With its iconic design cues, including the signature Mustang fastback silhouette and aggressive front grille, the Ford Mustang GT Premium 2022 stands out as a symbol of American muscle car heritage.",
          "Equipped with cutting-edge technology features, such as Ford SYNC® 4 infotainment system and Ford Co-Pilot360™ suite of driver-assist technologies, the Ford Mustang GT Premium 2022 ensures a connected and safe driving experience."]
      },
      {
        id: 21,
        type: 'car',
        brand: 'Chevrolet',
        model: 'Camaro',
        submodel: 'SS',
        year: 2022,
        horsepower: 455,
        space: 4,
        fuelType: 'Gasoline',
        rating: 4.8,
        mileage: 8000,
        price: 40,
        imageLocation: ['chevrolet_camaro.jpg', '', ''],
        aspects: ['Muscular Performance', 'Aggressive Design', 'Advanced Technology'],
        description: ["The Chevrolet Camaro SS 2022 delivers exhilarating performance with its 6.2-liter V8 engine producing 455 horsepower, offering impressive acceleration and a thrilling driving experience.",
          "With its aggressive design cues, including sculpted body lines and a distinctive front grille, the Chevrolet Camaro SS 2022 embodies the spirit of American muscle cars.",
          "Equipped with advanced technology features, such as Chevrolet Infotainment 3 system and available wireless charging, the Chevrolet Camaro SS 2022 keeps you connected and entertained on the road."]
      },
      {
        id: 22,
        type: 'truck',
        brand: 'Chevrolet',
        model: 'Silverado 1500',
        submodel: 'LTZ',
        year: 2023,
        horsepower: 355,
        space: 5,
        fuelType: 'Gasoline',
        rating: 4.7,
        mileage: 12000,
        price: 48,
        imageLocation: ['chevrolet_silverado.jpg', '', ''],
        aspects: ['Robust Capability', 'Refined Interior', 'Advanced Safety Features'],
        description: ["The Chevrolet Silverado 1500 LTZ 2023 combines robust capability with a refined interior, making it a versatile and comfortable truck for both work and everyday use.",
          "Featuring premium materials and thoughtful design, the Chevrolet Silverado 1500 LTZ 2023 offers a comfortable and upscale cabin that enhances the overall driving experience.",
          "Equipped with advanced safety features, such as Forward Collision Alert, Lane Keep Assist with Lane Departure Warning, and available Safety Alert Seat, the Chevrolet Silverado 1500 LTZ 2023 provides enhanced safety and peace of mind."]
      },
      {
        id: 23,
        type: 'suv',
        brand: 'Chevrolet',
        model: 'Equinox',
        submodel: 'Premier',
        year: 2022,
        horsepower: 170,
        space: 5,
        fuelType: 'Gasoline',
        rating: 4.5,
        mileage: 10000,
        price: 32,
        imageLocation: ['chevrolet_equinox.jpg', '', ''],
        aspects: ['Comfortable and Spacious', 'Modern Design', 'Advanced Safety'],
        description: ["The Chevrolet Equinox Premier 2022 offers a comfortable and spacious cabin, with supportive seating and ample cargo space, providing a pleasant driving experience for both driver and passengers.",
          "With its modern design elements, such as sleek lines and a bold front grille, the Chevrolet Equinox Premier 2022 showcases a contemporary and eye-catching presence on the road.",
          "Equipped with advanced safety technologies, including Lane Keep Assist, Rear Cross Traffic Alert, and available Forward Collision Alert, the Chevrolet Equinox Premier 2022 prioritizes safety and helps keep you protected on your journeys."]
      },
      {
        id: 24,
        type: 'car',
        brand: 'Honda',
        model: 'Civic',
        submodel: 'EX',
        year: 2022,
        horsepower: 174,
        space: 5,
        fuelType: 'Gasoline',
        rating: 4.7,
        mileage:8000,
        price: 20,
        imageLocation: ['honda_civic.jpg', '', ''],
        aspects: ['Efficiency and Reliability', 'Modern Design', 'Advanced Safety Features'],
        description: [
          "The Honda Civic EX 2022 offers exceptional efficiency and reliability, making it a practical choice for daily commuting and long journeys.",
          "Featuring a modern design with sleek lines and a distinctive front grille, the Honda Civic EX 2022 showcases a contemporary and stylish appearance.",
          "Equipped with advanced safety features, such as Honda Sensing suite, Lane Keeping Assist, and Adaptive Cruise Control, the Honda Civic EX 2022 provides enhanced safety and peace of mind on the road."
        ]
      },
      {
        id: 25,
        type: 'car',
        brand: 'Honda',
        model: 'Accord',
        submodel: 'Sport',
        year: 2022,
        horsepower: 192,
        space: 5,
        fuelType: 'Gasoline',
        rating: 4.6,
        mileage: 15000,
        price: 24,
        imageLocation: ['honda_accord.jpg', '', ''],
        aspects: ['Sporty Performance', 'Sleek Design', 'Advanced Technology'],
        description: [
          "The Honda Accord Sport 2022 delivers sporty performance with its powerful engine and responsive handling, offering an exciting driving experience.",
          "With its sleek and aerodynamic design, including bold character lines and a stylish front grille, the Honda Accord Sport 2022 exudes a sense of sophistication.",
          "Equipped with advanced technology features, such as Apple CarPlay, Android Auto, and HondaLink connectivity, the Honda Accord Sport 2022 keeps you connected and entertained on the go."
        ]
      },
      {
        id: 26,
        type: 'car',
        brand: 'Nissan',
        model: 'Altima',
        submodel: 'SL',
        year: 2022,
        horsepower: 188,
        space: 5,
        fuelType: 'Gasoline',
        rating: 4.6,
        mileage: 50000,
        price: 36,
        imageLocation: ['nissan_altima.jpg', '', ''],
        aspects: ['Comfort and Efficiency', 'Sleek Exterior', 'Advanced Safety Features'],
        description: [
          "The Nissan Altima SL 2022 offers a comfortable and efficient driving experience, with its spacious interior and fuel-efficient engine.",
          "Featuring a sleek and aerodynamic exterior design, including a distinctive V-motion grille and LED headlights, the Nissan Altima SL 2022 showcases modern styling.",
          "Equipped with advanced safety features, such as Intelligent Forward Collision Warning, Rear Automatic Braking, and Blind Spot Warning, the Nissan Altima SL 2022 prioritizes safety and helps prevent accidents."
        ]
      },
      {
        id: 27,
        type: 'suv',
        brand: 'Nissan',
        model: 'Rogue',
        submodel: 'SV',
        year: 2023,
        horsepower: 181,
        space: 5,
        fuelType: 'Gasoline',
        rating: 4.7,
        mileage: 40000,
        price: 60,
        imageLocation: ['nissan_rogue.jpg', '', ''],
        aspects: ['Versatility and Practicality', 'Modern Design', 'Advanced Safety'],
        description: [
          "The Nissan Rogue SV 2023 offers versatility and practicality with its spacious interior and flexible cargo capacity, making it a great choice for families and active lifestyles.",
          "Featuring a modern design with sleek lines and a bold front grille, the Nissan Rogue SV 2023 stands out on the road.",
          "Equipped with advanced safety technologies, including Intelligent Emergency Braking, Blind Spot Intervention, and Rear Cross Traffic Alert, the Nissan Rogue SV 2023 provides enhanced safety and peace of mind."
        ]
      },
      {
        id: 28,
        type: 'car',
        brand: 'Nissan',
        model: 'Maxima',
        submodel: 'Platinum',
        year: 2022,
        horsepower: 300,
        space: 5,
        fuelType: 'Gasoline',
        rating: 4.8,
        mileage: 10000,
        price: 55,
        imageLocation: ['nissan_maxima.jpg', '', ''],
        aspects: ['Powerful Performance', 'Luxurious Interior', 'Cutting-Edge Technology'],
        description: [
          "The Nissan Maxima Platinum 2022 offers powerful performance with its 300-horsepower engine and sport-tuned suspension, delivering an exhilarating driving experience.",
          "Featuring a luxurious and refined interior, including premium leather-appointed seats and ambient lighting, the Nissan Maxima Platinum 2022 provides a sophisticated and comfortable cabin.",
          "Equipped with cutting-edge technology features, such as NissanConnect infotainment system, Bose premium audio, and Intelligent Around View Monitor, the Nissan Maxima Platinum 2022 keeps you connected and entertained on every journey."
        ]
      },
      {
        id: 29,
        type: 'suv',
        brand: 'Jeep',
        model: 'Wrangler',
        submodel: 'Rubicon',
        year: 2022,
        horsepower: 285,
        space: 4,
        fuelType: 'Gasoline',
        rating: 4.8,
        mileage: 10000,
        price: 90,
        imageLocation: ['jeep_wrangler.jpg', '', ''],
        aspects: ['Off-Road Capability', 'Iconic Design', 'Open-Air Freedom'],
        description: [
          "The Jeep Wrangler Rubicon 2022 is renowned for its exceptional off-road capability, with features like heavy-duty axles, locking differentials, and enhanced ground clearance.",
          "Featuring the iconic Jeep design with a removable top and doors, the Jeep Wrangler Rubicon 2022 offers the exhilarating experience of open-air driving and a rugged yet stylish appearance.",
          "Equipped with advanced off-road systems, such as Rock-Trac 4x4 system, Tru-Lok electronic locking differentials, and Sway Bar Disconnect, the Jeep Wrangler Rubicon 2022 conquers challenging terrains with ease."
        ]
      },
      {
        id: 30,
        type: 'suv',
        brand: 'Jeep',
        model: 'Grand Cherokee',
        submodel: 'Limited',
        year: 2023,
        horsepower: 293,
        space: 5,
        fuelType: 'Gasoline',
        rating: 4.7,
        mileage: 2000,
        price: 210,
        imageLocation: ['jeep_grand_cherokee.jpg', '', ''],
        aspects: ['Luxurious Comfort', 'Advanced Technology', 'Impressive Performance'],
        description: [
          "The Jeep Grand Cherokee Limited 2023 offers luxurious comfort with its premium leather-trimmed seats, heated and ventilated front seats, and dual-zone automatic climate control.",
          "Featuring advanced technology features, such as Uconnect infotainment system, Apple CarPlay, Android Auto, and available Harman Kardon premium audio, the Jeep Grand Cherokee Limited 2023 keeps you connected and entertained on the go.",
          "Equipped with a powerful 3.6-liter V6 engine delivering 293 horsepower and an available Quadra-Drive II 4x4 system, the Jeep Grand Cherokee Limited 2023 provides impressive performance and capability."
        ]
      }     
];